# Site settings
title: kaleidoTricks
url: "https://kaleido.tricks.cx"
author:
  name: "Daniel C."
  email: "dan@tricks.cx"

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Exclude
exclude:
  - .gitignore
  - README.md

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Options
custom_header: false
custom_nav_footer: false
reverse: false
version: "0.1.1"
